services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: msv_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  postgresAS:
    container_name: postgresAS
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: sasa
      POSTGRES_DB: msv_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  msv-usuarios:
    container_name: msv-usuarios
    build:
      context: ./
      dockerfile: ./msv-usuarios/Dockerfile
    ports:
      - "8001:8001"
    #env_file:
    #  - ./msv-usuarios/.env
    networks:
      - spring
    depends_on:
      - mysql
    restart: always

  msv-cursos:
    container_name: msv-cursos
    build:
      context: ./
      dockerfile: ./msv-cursos/Dockerfile
    #image: cursos:latest
    ports:
      - "8002:8002"
    #env_file:
    #  - ./msv-cursos/.env
    networks:
      - spring
    depends_on:
      - postgresAS
      - msv-usuarios
    restart: always

volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres

networks:
  spring:
    external: true